spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://ustinterview.cs9mquaxf9k5.ap-south-1.rds.amazonaws.com:3306/ustinterview
    username: root
    password: password1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 5000